import type { Dictionary } from "./types";

export const en: Dictionary = {
  lang: "en",
  meta: {
    title: "Veni Tales — Personalized audio stories for your child",
    description:
      "AI-powered, professionally narrated personalized tales. Create magical stories with your child's name, interests and dreams.",
    ogTitle: "Veni Tales — Personalized audio stories for your child",
    ogDescription: "AI-powered personalized audio stories for your child.",
  },
  nav: {
    intro: "Intro",
    features: "Features",
    howItWorks: "How it works",
    download: "Download",
  },
  hero: {
    badge: "AI-powered",
    headingLine1: "Every night,",
    headingLine2: "a story made",
    headingLine3: "just for your child.",
    description:
      "It learns your child's name, interests and dreams. With professional narration, it creates stories just for them.",
    ctaHowItWorks: "How it works?",
    socialProof: "+1,000 happy families",
  },
  heroCarousel: {
    screenAlt1: "Veni app screen 1",
    screenAlt2: "Veni app screen 2",
    tablistLabel: "Screen preview",
  },
  onboarding: {
    heading: "Meet Veni",
    subtitle:
      "Take a peek at Veni's world in four steps — personalized stories and professional narration.",
    slides: [
      {
        title: "Stories made for your child",
        description:
          "Let your little hero step into the story! Every tale comes alive with colorful illustrations and warm narration.",
      },
      {
        title: "Your child is the hero!",
        description:
          "Your child can listen to a fun adventure in their favorite theme, starring as the hero.",
      },
      {
        title: "Learn languages while listening",
        description:
          "Cute foreign words can be hidden in the story. Your little explorer will love finding them.",
      },
      {
        title: "A value in every story",
        description:
          "A penguin teaching patience, a squirrel showing sharing… Characters whisper beautiful values while entertaining.",
      },
    ],
  },
  features: {
    label: "Why Veni Tales?",
    headingLine1: "More than an app,",
    headingLine2: "part of your family routine.",
    cards: [
      {
        title: "Personal stories",
        description:
          "Original tales featuring your child's name, interests and favorite characters.",
      },
      {
        title: "Professional voice",
        description:
          "Natural and warm tone. Calm for bedtime, lively during the day.",
      },
      {
        title: "Educational value",
        description:
          "Every story is built around themes like honesty, courage and friendship.",
      },
      {
        title: "Family friendly",
        description:
          "Age-appropriate content filters. Parental controls always active.",
      },
    ],
  },
  storyPreview: {
    label: "Have a taste",
    heading: "What kind of story does Veni Tales tell?",
    sampleLabel: "Sample story • for 6-year-old Ela",
    storyTitle: "Ela and the Star Hunter",
    storyP1:
      "Ela was looking out her window at night. She noticed a shooting star — but this star was no ordinary one. It gently tapped on the window and whispered:",
    storyDialogue1: "\u201CEla, can you help me? I\u2019m lost.\u201D",
    storyP2:
      "Ela threw her favorite blanket over her shoulders and opened the door. When she stepped into the garden in her pajamas, the little star was waiting. \u201CCould you be a star hunter?\u201D asked the star. Ela smiled.",
    storyDialogue2: "\u201CLet this be my first mission tonight.\u201D",
    totalDuration: "Total duration",
    durationValue: "4 minutes 12 seconds",
    aiAttribution: "Generated by AI",
  },
  howItWorks: {
    label: "How it works",
    headingLine1: "In one minute,",
    headingLine2: "a personalized story is ready.",
    steps: [
      {
        title: "Create a profile",
        description:
          "Complete the profile by entering name, age and gender for your child. Stories are personalized based on this info.",
      },
      {
        title: "Shape the story to your liking",
        description:
          "After choosing a theme or purpose, set the story's setting (nature, home, fantasy, city); finalize with length and other options in the app.",
      },
      {
        title: "Listen together",
        description:
          "The story is ready in seconds with professional narration. Lie down, listen and share together.",
      },
    ],
  },
  cta: {
    headingLine1: "Tonight,",
    headingLine2: "listen to the first tale.",
    description:
      "Download now, enter your child's name and listen to the first story made just for them.",
    appStoreFrom: "From App Store",
    download: "Download",
  },
  footer: {
    tagline: "AI-powered personalized audio stories for your child.",
    privacy: "Privacy policy",
    terms: "Terms of use",
    support: "Support",
    copyright: "All rights reserved.",
  },
};
